
###user creation
post http://localhost:5000/user-api/user
Content-Type: application/json

{
    "userType":"user",
    "username":"John Doe2",
    "email":"john.doe@example.com",
    "password":"qwerty",
    "description":"Software engineer with a passion for developing scalable web applications.",
    "picture":"https://example.com/path/to/picture.jpg",
    "academicDetails":{
        "passOutYear":"2010",
        "branch":"Computer Science"
    }
}


#### user login
post http://localhost:5000/user-api/login
Content-Type: application/json

{
    "userType":"user",
    "username":"ravi",
    "password":"ravi"
   
}

###reading articles of all users
get http://localhost:5000/user-api/articles


### write comment
post http://localhost:5000/user-api/comment/1708955782
Content-Type: application/json

{
   
    "username":"ravi",
    "comment":"Amazing content"
   
}
###
get http://localhost:5000/user-api/alumnicards

